var res = {
    LoginUI_json : "res/ui/LoginUI.json",
    BroadcastUI_json : "res/ui/BroadcastUI.json",
    effect_lockui_png : "res/effect/effect_lockui.png",
    effect_lockui_plist : "res/effect/effect_lockui.plist",
    LockUI_json : "res/ui/LockUI.json",
    gameroom2d_bg0_png : "res/ui/BackGround/gameroom2d_bg0.png",
    gameroom2d_bg1_png : "res/ui/BackGround/gameroom2d_bg1.png",
    gameroom2d_bg2_png : "res/ui/BackGround/gameroom2d_bg2.png",
    gameroom3d_bg0_png : "res/ui/BackGround/gameroom3d_bg0.png",
    gameroom3d_bg1_png : "res/ui/BackGround/gameroom3d_bg1.png",
    gameroom3d_bg2_png : "res/ui/BackGround/gameroom3d_bg2.png",
    gameroom_bg_desc2d0_png : "res/ui/BackGround/bg_desc2d0.png",
    gameroom_bg_desc2d1_png : "res/ui/BackGround/bg_desc2d1.png",
    gameroom_bg_desc2d2_png : "res/ui/BackGround/bg_desc2d2.png",
    gameroom_bg_desc3d0_png : "res/ui/BackGround/bg_desc3d0.png",
    gameroom_bg_desc3d1_png : "res/ui/BackGround/bg_desc3d1.png",
    gameroom_bg_desc3d2_png : "res/ui/BackGround/bg_desc3d2.png",
    mahjong_png : "res/ui/Mahjong.png",
    mahjong_plist : "res/ui/Mahjong.plist",
    playbackui_plist : "res/ui/PlaybackUI.plist",
    playbackui_png : "res/ui/PlaybackUI.png",
    biaoqing_png : "res/effect/biaoqing.png",
    biaoqing_plist : "res/effect/biaoqing.plist",
    common_talk_bg_png : "res/ui/Default/common_talk_bg.png",
    talk_frame_png : "res/ui/Default/talk_frame.png",
    talk_angle_png : "res/ui/Default/talk_angle.png",
    male_png : "res/ui/Default/male.png",
    famale_png : "res/ui/Default/famale.png",
    gameroom_tile_pointer_png : "res/ui/GameRoomUI/gameroom_tile_pointer.png",
    kingtilemark_png : "res/ui/GameRoomUI/kingtilemark.png",
    sezi_png : "res/effect/sezi.png",
    sezi_plist : "res/effect/sezi.plist",
    eye_png : "res/effect/eye.png",
    eye_plist : "res/effect/eye.plist",
    expression_png : "res/effect/expression.png",
    expression_plist : "res/effect/expression.plist",
    clubui_png : "res/ui/ClubUI.png",
    clubui_plist : "res/ui/ClubUI.plist",
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}
